### ISSUE TITLE
Questions on the formulation of the regression layer

### ISSUE THREAD

**Issue by zxc2012** [HKUDS/UrbanGPT#10]
Hello, Could you explain to me what st_start_id0 and st_start_id1 refer to in the prompt? 
I guess they have connection to equation 5.
![image](https://github.com/user-attachments/assets/eb67344c-95c9-4961-88a3-c5736699ca7b)
![image](https://github.com/user-attachments/assets/c6c7867d-f9bd-45da-8a67-ccef3786eab7)

**Comment by LZH-YS1998** [comment]
Hello. Yes, st_start_id0 and st_start_id1 are used to record the corresponding positions of the embeddings $H_{r,f}$ and $\Gamma_{r,f}$ in the prompt, respectively, for use in subsequent predictions.

**Comment by zxc2012** [comment]
Sorry. I mean which token in the prompt are they refering to? If I understands it correctly, st_start_id0 refers to the first <ST_Start>, which is covered by the sentence "To improve prediction accuracy, a spatio-temporal model is utilized to encode the historical bike data as tokens <ST_Start><ST_End>". It has nothing to do with the prediction part.

“Human: Given the historical data for bike flow over 12 time steps in a specific region of New York City, the recorded bike inflows are [12 8 9 15 10 12 14 9 6 12 25 20], and the recorded bike outflows are [5 12 12 15 10 11 6 9 4 6 10 15]. The recording time of the historical data is ’January 14, 2020, 12:00, Tuesday to January 14, 2020, 17:30, Tuesday, with data points recorded at 30-minute intervals’. Here is the region information: This region is located within the Staten Island borough district and encompasses various POIs within a one-kilometer radius, covering Education Facility, Cultural Facility, Commercial, Transportation Facility categories. We now aim to predict the bike inflow and outflow for the next 12 time steps during the time period of ’January 14, 2020, 18:00, Tuesday to January 14, 2020, 23:30, Tuesday, with data points recorded at 30-minute intervals’. To improve prediction accuracy, a spatio-temporal model is utilized to encode the historical bike data as tokens <ST_Start><ST_End>, where the first and the second tokens correspond to the representations of bike inflow and outflow. Please conduct an analysis of the traffic patterns in this region, taking into account the provided time and regional information, and then generate the predictions (the predictive tokens for regression).<ST_Start>”
“GPT: Based on the given information, the predictions (predicted tokens) of bike inflow and outflow in this region are <ST_Start>”

**Comment by LZH-YS1998** [comment]
Yes, st_start_id0 records the position of the first <ST_Start>. Therefore, st_start_token_pos1+1 : st_start_token_pos1+num_patches+1 corresponds to <ST_patch><ST_patch>, which serve as placeholders for $H_{r,f}$.

“Human: Given the historical data for bike flow over 12 time steps in a specific region of New York City, the recorded bike inflows are [12 8 9 15 10 12 14 9 6 12 25 20], and the recorded bike outflows are [5 12 12 15 10 11 6 9 4 6 10 15]. The recording time of the historical data is ’January 14, 2020, 12:00, Tuesday to January 14, 2020, 17:30, Tuesday, with data points recorded at 30-minute intervals’. Here is the region information: This region is located within the Staten Island borough district and encompasses various POIs within a one-kilometer radius, covering Education Facility, Cultural Facility, Commercial, Transportation Facility categories. We now aim to predict the bike inflow and outflow for the next 12 time steps during the time period of ’January 14, 2020, 18:00, Tuesday to January 14, 2020, 23:30, Tuesday, with data points recorded at 30-minute intervals’. To improve prediction accuracy, a spatio-temporal model is utilized to encode the historical bike data as tokens <ST_Start><ST_patch><ST_patch><ST_End>, where the first and the second tokens correspond to the representations of bike inflow and outflow. Please conduct an analysis of the traffic patterns in this region, taking into account the provided time and regional information, and then generate the predictions (the predictive tokens for regression).<ST_Start><ST_patch><ST_patch><ST_End>”
“GPT: Based on the given information, the predictions (predicted tokens) of bike inflow and outflow in this region are <ST_Start><ST_patch><ST_patch><ST_End>”

**Comment by zxc2012** [comment]
Thanks for that!
