### ISSUE TITLE
AttributeError: 'STLlamaConfig' object has no attribute 'lin_hidden_size'

### ISSUE THREAD

**Issue by agoodge** [HKUDS/UrbanGPT#11]
When I execute run_urbangpt.py with --model-name facebook/opt350m, I get the following error:

AttributeError: 'STLlamaConfig' object has no attribute 'lin_hidden_size'

All of the other arguments are left unchanged from the .sh file.

Can you tell me what is wrong? Thanks

**Comment by zxc2012** [comment]
I think the author mentioned the updated config file
![image](https://github.com/user-attachments/assets/76e1aa68-55f0-4d9b-9858-33af5c31a2df)

**Comment by LZH-YS1998** [comment]
If you have already downloaded all the files of the urbangpt model, can you run urbangpt_eval.sh normally? (sh urbangpt_eval.sh)
