### ISSUE TITLE
Questions about original dataset

### ISSUE THREAD

**Issue by zxc2012** [HKUDS/UrbanGPT#15]
Hello. Could you please give a description of each file in the origin ST dataset and how to preprocess it?
![image](https://github.com/user-attachments/assets/bb637a86-22aa-4d2c-bb89-0ede16abb0ed)

**Comment by LZH-YS1998** [comment]
Hello, Sure! You can find the process involving poi and rz_map detailed in the [instruction_generate.py](https://github.com/HKUDS/UrbanGPT/blob/main/instruction_generate/instruction_generate.py)

Additionally, the process for handling the ST dataset is outlined in the [load_dataset.py](https://github.com/HKUDS/UrbanGPT/blob/main/instruction_generate/load_dataset.py)

For example, the NYC_taxi dataset is structured as 263 x 105216 x 2, representing the number of regions, the number of timesteps (from 2016 to 2021, with each day divided into 48 timesteps), and the number of features (inflow and outflow), respectively. You can process the dataset as follows:
data_taxi_path = os.path.join('st_data/all_nyc_taxi_263x105216x2.npz')
data_taxi = np.load(data_taxi_path)['data']

**Comment by zxc2012** [comment]
Thanks for that!
