### ISSUE TITLE
LLMs 的损失计算

### ISSUE THREAD

**Issue by zhkzly** [HKUDS/UrbanGPT#16]
作者您好，我花了一些时间去阅读代码，想要了解具体的实现。但是当前我有一个疑问，在urbangpt/model/STLlama.py/STLlama.py中LLMs文本预测损失那里，似乎没有忽略IGNORE_INDEX，我没有看懂，想知道是否在某些位置处理了，或者我理解错了。十分感谢您。
![github_1](https://github.com/user-attachments/assets/27bf23ba-a7b5-4bd4-a127-52043d62f76d)
![github2](https://github.com/user-attachments/assets/0ad0975e-1bd3-49ce-81bd-b1666d82784a)

**Comment by LZH-YS1998** [comment]
您好，感谢您的关注。IGNORE_INDEX在vicuna/llama原本实现中会忽略的这部分loss的计算。

**Comment by zhkzly** [comment]
了解了，十分感谢！
