### ISSUE TITLE
Questions about the most original dataset

### ISSUE THREAD

**Issue by CK020717** [HKUDS/UrbanGPT#18]
![image](https://github.com/user-attachments/assets/472e624c-ede1-41c0-9462-dbf562692ced)
Hello. I want to know if there are any more original datasets beyond this dataset, and if I want to train my own dataset, what format should it be in? Alternatively, if I want to use an open-source dataset for training, how can I convert it into the format shown in the image?

**Comment by LZH-YS1998** [comment]
Hello. The image contains all of our original datasets. Please refer to [instruction_generate](https://github.com/HKUDS/UrbanGPT/tree/main/instruction_generate) to generate the text.
