### ISSUE TITLE
关于代码中机器人聊天模型的问题

### ISSUE THREAD

**Issue by CK020717** [HKUDS/UrbanGPT#20]
流量预测嵌入聊天机器人的部分是否可以剥离，是否可以跳过聊天机器人只使用流量预测

**Comment by LZH-YS1998** [comment]
UrbanGPT predicts through conversations. If you prefer direct predictions, please refer to  the traffic foundation model [OpenCity](https://github.com/HKUDS/OpenCity). Thank you.
