### ISSUE TITLE
多卡训练问题

### ISSUE THREAD

**Issue by save-me-ctrl-c** [HKUDS/UrbanGPT#4]
作者你好，我不咋接触大模型，这几天部署的时候，训练总是报多卡训练的问题，查阅之后说可能是多进程的问题，现在我想记录日志，请问应该在哪里添加设置呢，麻烦了

**Comment by save-me-ctrl-c** [comment]
![Snipaste_2024-04-09_10-30-44](https://github.com/HKUDS/UrbanGPT/assets/84692849/c60e835d-1413-4b05-ac8a-6ba19c8882c8)

**Comment by save-me-ctrl-c** [comment]
计算资源
![Snipaste_2024-04-09_11-11-21](https://github.com/HKUDS/UrbanGPT/assets/84692849/881e274a-c58a-48d0-b259-6558a7b6b9d1)
-----------------------------------------
![Snipaste_2024-04-09_10-38-51](https://github.com/HKUDS/UrbanGPT/assets/84692849/a0425332-a669-43a8-a1d9-0c8b0e54f9b4)
训练卡在这里，然后资源是用满了
![Snipaste_2024-04-09_10-45-22](https://github.com/HKUDS/UrbanGPT/assets/84692849/8116ad85-977e-483a-b143-c71f25678bc8)
最后报错
![Snipaste_2024-04-09_11-10-55](https://github.com/HKUDS/UrbanGPT/assets/84692849/0ba45c7e-893f-468e-9f48-52c8333a07f4)

**Comment by LZH-YS1998** [comment]
您好。我们之前没有遇到过类似问题，很抱歉无法提供详细的解决方案。
这可能是训练时多卡设置不正确，或者多卡不是分布在同一个节点上造成的。您可以参考github上的类似问题解决。
感谢。

**Comment by save-me-ctrl-c** [comment]
好的，非常感谢您的回复




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年4月12日(星期五) 下午5:17
收件人: ***@***.***&gt;; 
抄送: "cqupt ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [HKUDS/UrbanGPT] 多卡训练问题 (Issue #4)














 
您好。我们之前没有遇到过类似问题，很抱歉无法提供详细的解决方案。
 这可能是训练时多卡设置不正确，或者多卡不是分布在同一个节点上造成的。您可以参考github上的类似问题解决。
 感谢。
