### ISSUE TITLE
关于encoder的疑问

### ISSUE THREAD

**Issue by yuyongzi** [HKUDS/UrbanGPT#5]
尊敬的作者我有两个关于encoder的疑问：
1. 如何在训练过程中不使用st_encoder? ST_Llama.py中是否可以直接更改？
2. 请问有pretrain encoder的pipeline吗？我想要在其他数据集上试着训练~
谢谢！

**Comment by LZH-YS1998** [comment]
您好！
1. 可以的，直接在ST_Llama.py将st_encoder部分和embedding替代部分去掉即可。
2. 在[st_layers](https://github.com/HKUDS/UrbanGPT/blob/main/urbangpt/model/st_layers)的[ST_Encoder.py](https://github.com/HKUDS/UrbanGPT/blob/main/urbangpt/model/st_layers/ST_Encoder.py)部分有详细代码。

**Comment by yuyongzi** [comment]
好的谢谢！
