### ISSUE TITLE
A question regarding model construction

### ISSUE THREAD

**Issue by Dzysimon** [HKUDS/UrbanGPT#8]
Could you please correct a possible misunderstanding I might have: If there is already a small model capable of time series forecasting (a pre-trained ST_Encoder), what is the significance of constructing a large model to accomplish the same task based on it?

**Comment by LZH-YS1998** [comment]
Hello. Although there are many small-scale end-to-end spatio-temporal prediction models currently available, they often require a large amount of high-quality labeled data to generate spatio-temporal representations, making it difficult to generalize to zero-shot prediction scenarios. In this work, we introduce large language models (LLMs) to achieve multi-scenario zero-shot prediction tasks. The spatio-temporal encoder can effectively enhance the LLMs' temporal modeling capabilities. By combining the LLMs' excellent ability to understand text, we incorporate temporal and spatial information in natural language form within the prompt instructions. This enables UrbanGPT to capture the periodic time correlation patterns of different types of areas, thus achieving zero-shot prediction.
