### ISSUE TITLE
Question about GCN in ST_Enc.

### ISSUE THREAD

**Issue by IfReasonable** [HKUDS/UrbanGPT#9]
Hello, I read your wonderful paper but still have some question.

It seemes that the GCN is always unable in ST_Enc, does it conflict with the statement "spatio-temporal encoder is designed to be independent of graph structures when modeling spatial correlations" in the paper? Or there is any misunderstanding I made?

![Snipaste_2024-07-12_12-11-34](https://github.com/user-attachments/assets/8e51e131-a9e4-4788-b4f9-d0fbf7d66214)

Thanks!

**Comment by LZH-YS1998** [comment]
Hello, thank you for your interest in our work. In many real-world scenarios, the graph structure is unknown; therefore, the designed spatio-temporal encoder does not rely on graph structures. We model spatial correlations using prompt instructions  that contain spatial information, such as POIs.

**Comment by IfReasonable** [comment]
Thank's for your explanation!
